// ── Lounge user directory ──────────────────────────────────────
// Single source of truth for community member profiles. Looked up
// by display name from each thread/reply's author object so the
// thread/reply shapes can stay slim. Eventually each row will come
// from /api/lounge/users/:handle. Lives in its own file (no React
// components here) so Lounge.jsx and LoungeProfile.jsx can both
// import without breaking React Fast Refresh.
export const LOUNGE_USERS = {
  'rachel-p':   { handle: 'rachel-p',   name: 'Rachel P.',   initials: 'RP', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 4, location: 'Sugar Land, TX', avatarUrl: 'https://i.pravatar.cc/240?img=47', bio: 'Helping fellow DAs navigate the Houston metro. 4 yrs in temp work, 6 specialties, no regrets.', upvoteCount: 214, downvoteCount: 28, postCount: 12, commentCount: 83, followerCount: 47, followingCount: 12, joinedDate: 'Mar 2024', certifications: ['CPR/BLS', 'X-Ray', 'RDA'], openTo: ['Temp shifts', 'Permanent'] },
  'maya-c':     { handle: 'maya-c',     name: 'Maya C.',     initials: 'MC', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 3, location: 'Pearland, TX',   avatarUrl: 'https://i.pravatar.cc/240?img=48', bio: 'PSA queen. 3 years in. Pearland regulars only.', upvoteCount: 168, downvoteCount: 21, postCount: 8,  commentCount: 64, followerCount: 31, followingCount: 18, joinedDate: 'Jul 2024', certifications: ['CPR', 'X-Ray'], openTo: ['Temp shifts'] },
  'nia-g':      { handle: 'nia-g',      name: 'Nia G.',      initials: 'NG', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 5, location: 'Cypress, TX',    avatarUrl: 'https://i.pravatar.cc/240?img=49', bio: 'No lowballs. 5 years. Pediatric specialty.', upvoteCount: 245, downvoteCount: 34, postCount: 15, commentCount: 92, followerCount: 64, followingCount: 9,  joinedDate: 'Jan 2024', certifications: ['CPR/BLS', 'X-Ray', 'EFDA'], openTo: ['Temp shifts', 'Permanent'] },
  'tina-k':     { handle: 'tina-k',     name: 'Tina K.',     initials: 'TK', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 8, location: 'Katy, TX',       avatarUrl: 'https://i.pravatar.cc/240?img=44', bio: '8 years and counting. Mentor for new DAs in Houston.', upvoteCount: 358, downvoteCount: 46, postCount: 24, commentCount: 156, followerCount: 124, followingCount: 22, joinedDate: 'Sep 2023', certifications: ['CPR/BLS', 'X-Ray', 'EFDA', 'Nitrous'], openTo: ['Temp shifts'] },
  'jordan-t':   { handle: 'jordan-t',   name: 'Jordan T.',   initials: 'JT', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 7, location: 'Spring, TX',     avatarUrl: 'https://i.pravatar.cc/240?img=15', bio: 'Cement cleanup ninja. Open to weekday temp work.', upvoteCount: 226, downvoteCount: 28, postCount: 11, commentCount: 89, followerCount: 56, followingCount: 14, joinedDate: 'Feb 2024', certifications: ['CPR', 'X-Ray', 'RDA'], openTo: ['Temp shifts', 'Permanent'] },
  'kiara-m':    { handle: 'kiara-m',    name: 'Kiara M.',    initials: 'KM', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 4, location: 'Missouri City, TX', avatarUrl: 'https://i.pravatar.cc/240?img=20', bio: 'Orthotic evangelist. Front office crossover.', upvoteCount: 142, downvoteCount: 18, postCount: 7,  commentCount: 52, followerCount: 28, followingCount: 16, joinedDate: 'May 2024', certifications: ['CPR'], openTo: ['Temp shifts'] },
  'briana-l':   { handle: 'briana-l',   name: 'Briana L.',   initials: 'BL', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 2, location: 'Houston, TX',    avatarUrl: 'https://i.pravatar.cc/240?img=23', bio: 'New-ish. Soaking up everything in Houston.', upvoteCount: 73,  downvoteCount: 9,  postCount: 3,  commentCount: 28, followerCount: 9,  followingCount: 21, joinedDate: 'Aug 2024', certifications: ['CPR'], openTo: ['Temp shifts'] },
  'devon-v':    { handle: 'devon-v',    name: 'Devon V.',    initials: 'DV', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 3, location: 'Humble, TX',     avatarUrl: 'https://i.pravatar.cc/240?img=12', bio: 'Texas DA. Ortho lean.', upvoteCount: 86,  downvoteCount: 10, postCount: 4,  commentCount: 31, followerCount: 12, followingCount: 8,  joinedDate: 'Apr 2024', certifications: ['CPR', 'X-Ray'], openTo: ['Temp shifts'] },
  'lily-s':     { handle: 'lily-s',     name: 'Lily S.',     initials: 'LS', role: 'Dental Assistant',   roleShort: 'DA',  yearsExperience: 6, location: 'Houston, TX',    avatarUrl: 'https://i.pravatar.cc/240?img=32', bio: '6 years and finally found my people.', upvoteCount: 174, downvoteCount: 22, postCount: 9,  commentCount: 71, followerCount: 38, followingCount: 17, joinedDate: 'Nov 2023', certifications: ['CPR/BLS', 'X-Ray'], openTo: ['Temp shifts', 'Permanent'] },
  'anita-r':    { handle: 'anita-r',    name: 'Anita R.',    initials: 'AR', role: 'Dental Hygienist',   roleShort: 'RDH', yearsExperience: 6, location: 'Katy, TX',       avatarUrl: 'https://i.pravatar.cc/240?img=45', bio: 'RDH · Air-Flow advocate · prophy purist.', upvoteCount: 199, downvoteCount: 25, postCount: 10, commentCount: 76, followerCount: 52, followingCount: 11, joinedDate: 'Dec 2023', certifications: ['CPR/BLS', 'Local Anesthesia', 'Nitrous'], openTo: ['Temp shifts', 'Permanent'] },
  'jenna-m':    { handle: 'jenna-m',    name: 'Jenna M.',    initials: 'JM', role: 'Dental Hygienist',   roleShort: 'RDH', yearsExperience: 4, location: 'Houston, TX',    avatarUrl: 'https://i.pravatar.cc/240?img=46', bio: 'EMS Air-Flow lifer. Periodontal prevention nerd.', upvoteCount: 112, downvoteCount: 14, postCount: 5,  commentCount: 47, followerCount: 24, followingCount: 13, joinedDate: 'Jun 2024', certifications: ['CPR/BLS', 'Local Anesthesia'], openTo: ['Temp shifts'] },
  'dr-patel':   { handle: 'dr-patel',   name: 'Dr. Patel',   initials: 'DR', role: 'Dentist',            roleShort: 'DDS', yearsExperience: 12, location: 'Houston, TX',   avatarUrl: 'https://i.pravatar.cc/240?img=8',  bio: 'Practice owner · GP · associate hunter.', upvoteCount: 294, downvoteCount: 38, postCount: 18, commentCount: 64, followerCount: 87, followingCount: 31, joinedDate: 'Oct 2023', certifications: ['DDS', 'CPR/BLS'], openTo: ['Permanent'] },
  'dr-sanders': { handle: 'dr-sanders', name: 'Dr. Sanders', initials: 'AS', role: 'Dentist',            roleShort: 'DDS', yearsExperience: 8, location: 'Sugar Land, TX', avatarUrl: 'https://i.pravatar.cc/240?img=11', bio: 'GP · GowGates devotee · associate at SLD.', upvoteCount: 220, downvoteCount: 28, postCount: 9,  commentCount: 53, followerCount: 41, followingCount: 18, joinedDate: 'Jan 2024', certifications: ['DDS', 'CPR/BLS', 'Nitrous'], openTo: ['Temp shifts', 'Permanent'] },
  'dr-vance':   { handle: 'dr-vance',   name: 'Dr. Vance',   initials: 'DR', role: 'Dentist',            roleShort: 'DDS', yearsExperience: 15, location: 'Bellaire, TX',  avatarUrl: 'https://i.pravatar.cc/240?img=14', bio: 'Practice owner · CDT code watcher.', upvoteCount: 268, downvoteCount: 34, postCount: 14, commentCount: 41, followerCount: 78, followingCount: 22, joinedDate: 'Aug 2023', certifications: ['DDS', 'CPR/BLS'], openTo: ['Permanent'] },
  'jenna-e':    { handle: 'jenna-e',    name: 'Jenna E.',    initials: 'JE', role: 'Front Office',       roleShort: 'FO',  yearsExperience: 6, location: 'Sugar Land, TX', avatarUrl: 'https://i.pravatar.cc/240?img=24', bio: 'CDT codes are my love language.', upvoteCount: 154, downvoteCount: 20, postCount: 8,  commentCount: 56, followerCount: 32, followingCount: 14, joinedDate: 'Mar 2024', certifications: ['DANB CFOA'], openTo: ['Permanent'] },
  'brittany-r': { handle: 'brittany-r', name: 'Brittany R.', initials: 'BR', role: 'Front Office',       roleShort: 'FO',  yearsExperience: 9, location: 'Pearland, TX',   avatarUrl: 'https://i.pravatar.cc/240?img=27', bio: 'Insurance verifier · billing · ops.', upvoteCount: 204, downvoteCount: 26, postCount: 11, commentCount: 72, followerCount: 49, followingCount: 16, joinedDate: 'Nov 2023', certifications: ['DANB CFOA', 'CDT'], openTo: ['Permanent'] },
};

// Look up a user by display name. Returns undefined for anon authors
// or names not in the directory.
export function lookupLoungeUser(name) {
  if (!name) return undefined;
  for (const u of Object.values(LOUNGE_USERS)) {
    if (u.name === name) return u;
  }
  return undefined;
}
